Update continue_aunError

diff --git a/vars/continue_aunError b/vars/continue_aunError
--- a/vars/continue_aunError
+++ b/vars/continue_aunError
@@ -21,9 +21,14 @@ pipeline {
                        echo "ELSE...."
                        stageResult = 'FAILURE'
                         echo "PRODUCT not Available for Testing" + stageResult
+                        /************************/
+                        catchError(buildResult: 'SUCCESS', stageResult: 'SUCCESS') {  --> entra pero lo pone en verde
+                                               echo "catchError...."
+                                               sh "exit 1"
+                                        }
+                        /***********************/
                         
-                        
-                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
+                        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {  --> entra pero lo pone en rojo
                                                echo "catchError...."
                                                sh "exit 1"
                                         }
